name = "lv-fa-import"
main = "src/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lvfa_import"
database_id = "3033f2ce-87d3-4d10-94ec-c6b5279c0048"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMPORT_BUCKET"
bucket_name = "lv-fa-import"

[vars]
APP_NAME = "Letecký vykřičník & FlyAlert"
PUBLIC_BASE_URL = "https://import.leteckyvykricnik.cz"
ADMIN_EMAIL = "letecky.vykricnik@gmail.com"
# For local testing only, you may override this with ADMIN_EMAILS in .dev.vars (comma-separated).
EMAIL_FROM = "no-reply@leteckyvykricnik.cz"
MAX_FILES = "20"
MAX_FILE_MB = "25"
GOOGLE_DRIVE_FOLDER_ID = "14OfUk90UfPR30JOC0Bmi8eGaWEnyWQ7y"
