const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();
const MAX_FILES_DEFAULT=20, MAX_FILE_MB_DEFAULT=25;
const ADMIN_COOKIE='lvfa_import_admin';

function envNumber(env,k,f){const n=Number(env[k]);return Number.isFinite(n)&&n>0?n:f}
function email(v){return String(v||'').trim().toLowerCase()}
function safe(v,max=160){return String(v||'').trim().replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').replace(/[. ]+$/g,'').slice(0,max)}
function isImageMime(v){return ['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(String(v||'').toLowerCase())}
function extFrom(name,mime){const n=String(name||'').toLowerCase(); const m=n.match(/\.(jpg|jpeg|png|webp|heic|heif)$/); if(m)return '.'+m[1]; return ({'image/jpeg':'.jpeg','image/png':'.png','image/webp':'.webp','image/heic':'.heic','image/heif':'.heif'}[String(mime||'').toLowerCase()]||'.jpeg')}
function cleanFilenamePart(v){return safe(v,120)}
function normalizedSource(v){const s=String(v||'').trim();return /^gmail$/i.test(s)?'':s}
const CATS={photos:{suffix:'',label:'Fotografie'},stories:{suffix:'_Stories',label:'Stories'},events:{suffix:'_Events',label:'Events'},contest:{suffix:'_Soutez',label:'Soutěž'}};
function normalizeCategory(v){const x=String(v||'').trim().toLowerCase();return CATS[x]?x:'photos'}
function buildFilename(p, extension='.jpeg'){
  const parts=[cleanFilenamePart(p.photographer),cleanFilenamePart(p.instagram),cleanFilenamePart(p.airline),cleanFilenamePart(p.aircraft)].filter(Boolean);
  const seq=Number(p.sequence); const suffix=Number.isInteger(seq)&&seq>=2?`_${seq}`:'';
  return `${parts.length?parts.join('_'):'photo'}${suffix}_Import${extension}`;
}
function identity(n){return String(n||'').replace(/\.(jpe?g|png|webp|heic|heif)$/i,'').toLowerCase()}

function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function fromB64url(s){const x=String(s).replace(/-/g,'+').replace(/_/g,'/')+'===';const b=atob(x.slice(0,x.length-(x.length%4)));return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function hmac(secret,msg){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(msg)))}
function sessionSecret(env,request){if(env.SESSION_SECRET)return String(env.SESSION_SECRET);const h=new URL(request.url).hostname;return (h==='localhost'||h==='127.0.0.1')?'lv-fa-import-local-development-session-secret-change-me':''}
async function signCookie(env,payload,request){const secret=sessionSecret(env,request);if(!secret)throw new Error('SESSION_SECRET_NOT_CONFIGURED');const sig=b64url(await hmac(secret,payload));return b64url(new TextEncoder().encode(`${payload}.${sig}`))}
async function verifyCookie(env,request){const raw=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${ADMIN_COOKIE}=`))?.split('=').slice(1).join('=');const secret=sessionSecret(env,request);if(!raw||!secret)return null;try{const text=new TextDecoder().decode(fromB64url(decodeURIComponent(raw)));const firstDot=text.indexOf('.');const lastDot=text.lastIndexOf('.');if(firstDot<=0||lastDot<=firstDot)return null;const exp=text.slice(0,firstDot);const mail=text.slice(firstDot+1,lastDot);const sig=text.slice(lastDot+1);if(!exp||Number(exp)<Date.now()||!isAllowedAdmin(env,mail))return null;const expected=await hmac(secret,`${exp}.${mail}`);const actual=fromB64url(sig);if(expected.length!==actual.length)return null;let d=0;for(let i=0;i<expected.length;i++)d|=expected[i]^actual[i];return d===0?{email:mail}:null}catch{return null}}
function cookie(name,value,maxAge,secure=true){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; SameSite=Lax; HttpOnly${secure?'; Secure':''}`}
function baseUrl(env,request){const u=new URL(request.url);if(u.hostname==='localhost'||u.hostname==='127.0.0.1')return u.origin;return String(env.PUBLIC_BASE_URL||u.origin).replace(/\/$/,'')}

function oauthRedirect(env,state,request){const redirect=`${baseUrl(env,request)}/api/auth/google/callback`;const p=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'openid email profile',access_type:'online',prompt:'select_account',state});return `https://accounts.google.com/o/oauth2/v2/auth?${p}`}
async function googleToken(env,code,request){const redirect=`${baseUrl(env,request)}/api/auth/google/callback`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:redirect,grant_type:'authorization_code'})});if(!r.ok)throw new Error('GOOGLE_TOKEN_FAILED');return r.json()}
async function googleUser(access){const r=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw new Error('GOOGLE_USERINFO_FAILED');return r.json()}
function adminEmails(env){const raw=String(env.ADMIN_EMAILS||env.ADMIN_EMAIL||'');return raw.split(',').map(email).filter(Boolean)}
function isAllowedAdmin(env,address){return adminEmails(env).includes(email(address))}
async function authRequired(env,request){return verifyCookie(env,request)}

async function emailLogoAttachment(env){const r=await env.ASSETS.fetch(new Request(new URL('/assets/logo-email.png','https://lv-fa-import.internal')));if(!r.ok)throw new Error('EMAIL_LOGO_NOT_FOUND');const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return {filename:'lv-fa-logo.png',content:btoa(binary),content_type:'image/png',content_id:'lvfa-logo'}}
async function sendEmail(env,to,subject,html){if(!env.RESEND_API_KEY||!env.EMAIL_FROM)throw new Error('EMAIL_NOT_CONFIGURED');const attachment=await emailLogoAttachment(env);const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject,html,attachments:[attachment]})});if(!r.ok){const detail=await r.text().catch(()=> '');throw new Error(`RESEND_${r.status}${detail?`_${detail.slice(0,180)}`:''}`)}return r.json()}
function resultEmail(sub,approved,rejected){const subject=`Potvrzení o přijetí fotografií / Photo Submission Confirmation`;const count=Number(approved||0);const logo='<div style="margin-top:24px"><img src="cid:lvfa-logo" alt="Letecký vykřičník &amp; FlyAlert" width="300" style="display:block;width:300px;max-width:100%;height:auto;border:0"></div>';const html=`<!doctype html><html><body style="margin:0;background:#f6f6f4;font-family:Arial,sans-serif;color:#111"><div style="max-width:680px;margin:32px auto;background:#fff;border:1px solid #ddd;padding:30px"><p><em>English version below.</em></p><p>Dobrý den,</p><p>Letecký vykřičník &amp; FlyAlert děkuje za Váš zájem o poskytnutí Vašich fotografií.</p><p>K použití na profilech byly vybrány fotografie v celkovém počtu: <strong>${count}</strong>. Tyto snímky budou archivovány do doby jejich zveřejnění.</p><p>U všech příspěvků, ve kterých budou Vaše fotografie použity, budete vždy uveden/a jako autor/ka.</p><p><em>Tato zpráva byla vygenerována automaticky, neodpovídejte na ni.</em></p><p><strong>Letecký vykřičník &amp; FlyAlert</strong><br>leteckyvykricnik.cz<br>E-mail: <a href="mailto:info@leteckyvykricnik.cz">info@leteckyvykricnik.cz</a></p>${logo}<hr style="border:0;border-top:1px solid #ddd;margin:28px 0"><p><strong>English version</strong></p><p>Hello,</p><p>Thank you for your interest in sharing your photos with Letecký vykřičník &amp; FlyAlert.</p><p>Number of selected photos for use on our profiles: <strong>${count}</strong>. These photos will be archived until they are published.</p><p>You will always be credited as the author in all posts where your photos are used.</p><p><em>This is an automatically generated email. Please do not reply to this message.</em></p><p><strong>Letecký vykřičník &amp; FlyAlert</strong><br>leteckyvykricnik.cz<br>Email: <a href="mailto:info@leteckyvykricnik.cz">info@leteckyvykricnik.cz</a></p>${logo}</div></body></html>`;return {subject,html}}


async function publicCreate(request,env){
 const body=await request.json().catch(()=>({})); const name=safe(body.name,120); const addr=email(body.email); const instagram=safe(body.instagram,160); const language=body.language==='en'?'en':'cs'; const consent=body.consent===true; const files=Array.isArray(body.files)?body.files:[]; const maxFiles=envNumber(env,'MAX_FILES',MAX_FILES_DEFAULT),maxBytes=envNumber(env,'MAX_FILE_MB',MAX_FILE_MB_DEFAULT)*1024*1024;
 if(!name||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(addr)||!consent)return json({error:'INVALID_CONTACT_OR_CONSENT'},400); if(!files.length||files.length>maxFiles)return json({error:'INVALID_FILE_COUNT',maxFiles},400);
 for(const f of files){if(!f||!isImageMime(f.mimeType)||!f.name||Number(f.size)<=0||Number(f.size)>maxBytes||!f.meta?.airline)return json({error:'INVALID_PHOTO_METADATA',message:'Každá fotografie musí mít vyplněnou aerolinku / letiště.'},400)}
 const id=`IMP-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}-${uuid().slice(0,6).toUpperCase()}`; const created=now(); const stm=[env.DB.prepare('INSERT INTO submissions (id,name,email,language,instagram,consent_at,status,total_files,created_at) VALUES (?,?,?,?,?,?,?, ?,?)').bind(id,name,addr,language,instagram,created,'UPLOADING',files.length,created)]; const rows=[];
 for(const f of files){const pid=uuid();const original=safe(f.name);const key=`imports/${created.slice(0,4)}/${created.slice(5,7)}/${id}/${pid}-${original}`;const m=f.meta||{};rows.push({id:pid,key,original,mime:f.mimeType,size:Number(f.size)});stm.push(env.DB.prepare('INSERT INTO photos (id,submission_id,storage_key,original_name,mime_type,size_bytes,status,photographer,instagram,airline,aircraft,note,category,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(pid,id,key,original,f.mimeType,Number(f.size),'UPLOADING',safe(name,120),safe(instagram,160),safe(m.airline,160),safe(m.aircraft||'',160),'','photos',created))}
 await env.DB.batch(stm); const uploads=rows.map((r,index)=>({id:r.id,index,name:r.original,uploadUrl:`/api/public/uploads/${encodeURIComponent(r.id)}`}));return json({ok:true,submissionId:id,uploads},201)
}
async function publicUpload(request,env,id){
 const p=await env.DB.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();
 if(!p)return json({error:'NOT_FOUND'},404);
 if(p.status!=='UPLOADING')return json({error:'UPLOAD_NOT_ALLOWED'},409);
 const length=Number(request.headers.get('Content-Length')||0);
 if(length && length!==Number(p.size_bytes))return json({error:'SIZE_MISMATCH',expected:Number(p.size_bytes),received:length},400);
 try{
   const result=await env.IMPORT_BUCKET.put(p.storage_key,request.body,{httpMetadata:{contentType:p.mime_type}});
   if(!result)return json({error:'R2_WRITE_FAILED'},502);
   return json({ok:true,photoId:id});
 }catch(e){
   console.error('R2_UPLOAD_PROXY_FAILED',id,e);
   return json({error:'R2_WRITE_FAILED',message:String(e?.message||e)},502);
 }
}
async function publicComplete(request,env,id){const sub=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!sub)return json({error:'NOT_FOUND'},404);if(sub.status!=='UPLOADING')return json({error:'ALREADY_COMPLETED'},409);const ps=await env.DB.prepare('SELECT * FROM photos WHERE submission_id=?').bind(id).all();for(const p of ps.results||[]){const o=await env.IMPORT_BUCKET.head(p.storage_key);if(!o||Number(o.size)!==Number(p.size_bytes))return json({error:'UPLOAD_INCOMPLETE',photoId:p.id,filename:p.original_name},400)}await env.DB.batch([env.DB.prepare("UPDATE photos SET status='UPLOADED' WHERE submission_id=?").bind(id),env.DB.prepare("UPDATE submissions SET status='READY_FOR_REVIEW',completed_at=? WHERE id=?").bind(now(),id)]);return json({ok:true,submissionId:id})}

async function adminList(request,env){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const r=await env.DB.prepare('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 300').all();return json({submissions:r.results||[]})}
async function adminDetail(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const r=await env.DB.prepare('SELECT * FROM photos WHERE submission_id=? ORDER BY created_at').bind(id).all();return json({submission:s,photos:(r.results||[]).map(p=>({...p,previewUrl:`/api/admin/photos/${encodeURIComponent(p.id)}/preview`}))})}
async function adminDeleteSubmission(request,env,id){
 if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);
 const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();
 if(!s)return json({error:'NOT_FOUND'},404);
 const r=await env.DB.prepare('SELECT id,storage_key,status,archive_id FROM photos WHERE submission_id=?').bind(id).all();
 const photos=r.results||[];
 const protectedPhotos=photos.filter(p=>p.status==='ARCHIVED'||p.archive_id);
 let removedFromImport=0;
 try{
   for(const p of photos){
     if(p.status==='ARCHIVED'||p.archive_id)continue;
     if(p.storage_key){await env.IMPORT_BUCKET.delete(p.storage_key);removedFromImport++;}
   }
   await env.DB.batch([
     env.DB.prepare('DELETE FROM photos WHERE submission_id=?').bind(id),
     env.DB.prepare('DELETE FROM submissions WHERE id=?').bind(id)
   ]);
 }catch(e){
   console.error('DELETE_SUBMISSION_ERROR',e);
   return json({error:'DELETE_FAILED',message:'Zásilku se nepodařilo kompletně smazat. Záznam v administraci zůstává zachován.'},500);
 }
 return json({ok:true,deletedPhotos:photos.length-protectedPhotos.length,keptArchivedPhotos:protectedPhotos.length});
}
async function adminUpdatePhoto(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const b=await request.json().catch(()=>({}));const p=await env.DB.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!p)return json({error:'NOT_FOUND'},404);const m={photographer:safe(b.photographer,120),instagram:safe(b.instagram,120),source:safe(b.source,160),airline:safe(b.airline,160),aircraft:safe(b.aircraft,160),note:safe(b.note,500),category:normalizeCategory(b.category)};if(!m.photographer||!m.airline)return json({error:'REQUIRED_FIELDS'},400);await env.DB.prepare('UPDATE photos SET photographer=?,instagram=?,source=?,airline=?,aircraft=?,note=?,category=? WHERE id=?').bind(m.photographer,m.instagram,m.source,m.airline,m.aircraft,m.note,m.category,id).run();return json({ok:true})}
async function maybeSendRejectedOnly(env,id){const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s||s.email_status==='SENT')return;const c=await env.DB.prepare("SELECT SUM(status='APPROVED') approved,SUM(status='REJECTED') rejected,SUM(status='UPLOADED') pending FROM photos WHERE submission_id=?").bind(id).first();if(Number(c?.pending||0)!==0||Number(c?.approved||0)!==0)return;const mail=resultEmail(s,0,Number(c?.rejected||0));try{await sendEmail(env,s.email,mail.subject,mail.html);await env.DB.prepare("UPDATE submissions SET email_status='SENT',email_sent_at=? WHERE id=?").bind(now(),id).run()}catch(e){await env.DB.prepare("UPDATE submissions SET email_status='FAILED',email_error=? WHERE id=?").bind(String(e?.message||e),id).run()}}
async function adminReview(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const b=await request.json().catch(()=>({}));const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const list=Array.isArray(b.photos)?b.photos:[];const stm=[];for(const x of list){if(!['APPROVED','REJECTED','UPLOADED'].includes(x.status))continue;stm.push(env.DB.prepare('UPDATE photos SET status=?,review_note=?,reviewed_at=? WHERE id=? AND submission_id=?').bind(x.status,safe(x.note,500),now(),x.id,id))}if(stm.length)await env.DB.batch(stm);const c=await env.DB.prepare("SELECT SUM(status='APPROVED') approved,SUM(status='REJECTED') rejected,SUM(status='UPLOADED') pending FROM photos WHERE submission_id=?").bind(id).first();const pending=Number(c?.pending||0),approved=Number(c?.approved||0),rejected=Number(c?.rejected||0);const status=pending?'IN_REVIEW':'REVIEWED';await env.DB.prepare('UPDATE submissions SET status=?,approved_files=?,rejected_files=?,review_started_at=COALESCE(review_started_at,?) WHERE id=?').bind(status,approved,rejected,now(),id).run();if(status==='REVIEWED')await maybeSendRejectedOnly(env,id);return json({ok:true,status,approved,rejected,pending})}

function pkcs8ToPem(raw){return raw}
async function googleAccessToken(env){const email=env.GOOGLE_SERVICE_ACCOUNT_EMAIL,keyPem=pkcs8ToPem(env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY||'');if(!email||!keyPem)throw new Error('GOOGLE_SERVICE_ACCOUNT_NOT_CONFIGURED');const pem=keyPem.replace(/\\n/g,'\n');const b64=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s/g,'');const der=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',der,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const enc=v=>b64url(new TextEncoder().encode(v));const head=enc(JSON.stringify({alg:'RS256',typ:'JWT'}));const claim=enc(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/drive',aud:'https://oauth2.googleapis.com/token',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600}));const input=`${head}.${claim}`;const sig=b64url(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(input))));const jwt=`${input}.${sig}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});if(!r.ok)throw new Error('GOOGLE_SERVICE_TOKEN_FAILED');return (await r.json()).access_token}
async function driveListNames(token,parent){const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(`'${parent.replace(/'/g,"\\'")}' in parents and trashed = false`)}&fields=files(id,name)&pageSize=1000`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('DRIVE_LIST_FAILED');const j=await r.json();return new Set((j.files||[]).map(x=>identity(x.name)))}
async function driveFindOrCreateFolder(token,parent,name){const q=`'${parent.replace(/'/g,"\\'")}' in parents and name='${name.replace(/'/g,"\\'")}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)&pageSize=10`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('DRIVE_FOLDER_LIST_FAILED');const j=await r.json();if(j.files?.[0]?.id)return j.files[0].id;const c=await fetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name,parents:[parent],mimeType:'application/vnd.google-apps.folder'})});if(!c.ok)throw new Error('DRIVE_FOLDER_CREATE_FAILED');return (await c.json()).id}
async function archiveFolder(token,root,category){const c=normalizeCategory(category);if(c==='photos')return root;return driveFindOrCreateFolder(token,root,CATS[c].label)}
async function driveUpload(token,parent,filename,mime,bytes){const boundary=`lvfa_${uuid()}`;const meta=JSON.stringify({name:filename,parents:[parent],properties:{source:'LV-FA Import'}});const pre=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`;const post=`\r\n--${boundary}--`;const body=new Blob([pre,bytes,post]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!r.ok)throw new Error(`DRIVE_UPLOAD_${r.status}`);return r.json()}
async function adminArchive(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const ps=await env.DB.prepare("SELECT * FROM photos WHERE submission_id=? AND status='APPROVED'").bind(id).all();if(!ps.results?.length)return json({error:'NO_APPROVED_PHOTOS'},400);const token=await googleAccessToken(env);await env.DB.prepare("UPDATE submissions SET status='ARCHIVING',archive_started_at=? WHERE id=?").bind(now(),id).run();let ok=0,failed=0;for(const p of ps.results){try{const o=await env.IMPORT_BUCKET.get(p.storage_key);if(!o)throw new Error('IMPORT_FILE_NOT_FOUND');const parent=await archiveFolder(token,env.GOOGLE_DRIVE_FOLDER_ID,p.category);const existing=await driveListNames(token,parent);const ext=extFrom(p.original_name,p.mime_type);const base={photographer:p.photographer,instagram:p.instagram,airline:p.airline,aircraft:p.aircraft};let filename=buildFilename(base,ext);if(existing.has(identity(filename))){for(let n=2;n<10000;n++){const c=buildFilename({...base,sequence:n},ext);if(!existing.has(identity(c))){filename=c;break}}}if(existing.has(identity(filename)))throw new Error('FILENAME_SEQUENCE_EXHAUSTED');const result=await driveUpload(token,parent,filename,p.mime_type,await o.arrayBuffer());existing.add(identity(filename));await env.DB.prepare("UPDATE photos SET status='ARCHIVED',archive_id=?,archived_at=?,archive_error=NULL WHERE id=?").bind(result.id||'',now(),p.id).run();ok++}catch(e){failed++;await env.DB.prepare("UPDATE photos SET status='ARCHIVE_FAILED',archive_error=? WHERE id=?").bind(String(e?.message||e),p.id).run()}}
const final=failed?'ARCHIVE_FAILED':'ARCHIVED';await env.DB.prepare('UPDATE submissions SET status=?,archive_completed_at=? WHERE id=?').bind(final,now(),id).run();if(!failed){const counts=await env.DB.prepare("SELECT SUM(status='ARCHIVED') approved,SUM(status='REJECTED') rejected FROM photos WHERE submission_id=?").bind(id).first();const mail=resultEmail(s,Number(counts?.approved||ok),Number(counts?.rejected||0));try{await sendEmail(env,s.email,mail.subject,mail.html);await env.DB.prepare("UPDATE submissions SET email_status='SENT',email_sent_at=? WHERE id=?").bind(now(),id).run()}catch(e){await env.DB.prepare("UPDATE submissions SET email_status='FAILED',email_error=? WHERE id=?").bind(String(e?.message||e),id).run()}}return json({ok:true,archived:ok,failed,status:final})}
async function preview(request,env,id){if(!await authRequired(env,request))return new Response('Unauthorized',{status:401});const p=await env.DB.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!p)return new Response('Not found',{status:404});const o=await env.IMPORT_BUCKET.get(p.storage_key);if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'Content-Type':p.mime_type,'Cache-Control':'private,max-age=60'}})}

async function api(request,env){const u=new URL(request.url),p=u.pathname;
 if(request.method==='GET'&&p==='/api/auth/google'){const raw=`${Date.now()+600000}.${uuid()}`;const state=await signCookie(env,raw,request);const secure=new URL(request.url).protocol==='https:';return new Response(null,{status:302,headers:{Location:oauthRedirect(env,state,request),'Set-Cookie':cookie('lvfa_oauth_state',state,600,secure)}})}
 if(request.method==='GET'&&p==='/api/auth/google/callback'){const code=u.searchParams.get('code'),state=u.searchParams.get('state');const stateCookie=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('lvfa_oauth_state='))?.split('=').slice(1).join('=');if(!code||!state||!stateCookie||state!==decodeURIComponent(stateCookie))return Response.redirect(`${baseUrl(env,request)}/admin?login=failed`,302);try{const token=await googleToken(env,code,request);const user=await googleUser(token.access_token);if(!isAllowedAdmin(env,user.email))return Response.redirect(`${baseUrl(env,request)}/admin?login=denied`,302);const value=await signCookie(env,`${Date.now()+1000*60*60*24*7}.${email(user.email)}`,request);const secure=new URL(request.url).protocol==='https:';const headers=new Headers();headers.set('Location',`${baseUrl(env,request)}/admin?login=success`);headers.set('Set-Cookie',cookie(ADMIN_COOKIE,value,604800,secure));headers.set('Cache-Control','no-store');return new Response(null,{status:302,headers})}catch(e){console.error('GOOGLE_CALLBACK_ERROR',e);return Response.redirect(`${baseUrl(env,request)}/admin?login=failed`,302)}}
 if(request.method==='POST'&&p==='/api/auth/logout')return new Response(null,{status:204,headers:{'Set-Cookie':cookie(ADMIN_COOKIE,'',0,new URL(request.url).protocol==='https:')}});
 if(request.method==='GET'&&p==='/api/auth/me'){const s=await authRequired(env,request);return json(s?{authenticated:true,email:s.email}:{authenticated:false},s?200:401)}
 if(request.method==='POST'&&p==='/api/public/submissions')return publicCreate(request,env);
 if(request.method==='PUT'&&p.startsWith('/api/public/uploads/'))return publicUpload(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='POST'&&p.startsWith('/api/public/submissions/')&&p.endsWith('/complete'))return publicComplete(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='GET'&&p==='/api/admin/submissions')return adminList(request,env);
 if(request.method==='GET'&&p.startsWith('/api/admin/submissions/'))return adminDetail(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='DELETE'&&p.startsWith('/api/admin/submissions/'))return adminDeleteSubmission(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='PATCH'&&p.startsWith('/api/admin/photos/'))return adminUpdatePhoto(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='POST'&&p.startsWith('/api/admin/submissions/')&&p.endsWith('/review'))return adminReview(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='POST'&&p.startsWith('/api/admin/submissions/')&&p.endsWith('/archive'))return adminArchive(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='GET'&&p.startsWith('/api/admin/photos/')&&p.endsWith('/preview'))return preview(request,env,decodeURIComponent(p.split('/')[4]));
 return json({error:'NOT_FOUND'},404)}

export default {async fetch(request,env){try{const u=new URL(request.url);if(u.pathname.startsWith('/api/'))return await api(request,env);if(u.pathname==='/admin'||u.pathname==='/admin/')return env.ASSETS.fetch(new Request(new URL('/admin.html',u).toString(),request));if(u.pathname==='/'||u.pathname==='/en'||u.pathname==='/en/')return env.ASSETS.fetch(new Request(new URL('/index.html',u).toString(),request));return env.ASSETS.fetch(request)}catch(e){console.error(e);return json({error:'INTERNAL_ERROR',message:String(e?.message||e)},500)}}};
