import { AwsClient } from 'aws4fetch';

const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();
const MAX_FILES_DEFAULT=30, MAX_FILE_MB_DEFAULT=25;
const ADMIN_COOKIE='lvfa_import_admin';

function envNumber(env,k,f){const n=Number(env[k]);return Number.isFinite(n)&&n>0?n:f}
function email(v){return String(v||'').trim().toLowerCase()}
function safe(v,max=160){return String(v||'').trim().replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').replace(/[. ]+$/g,'').slice(0,max)}
function isImageMime(v){return ['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(String(v||'').toLowerCase())}
function extFrom(name,mime){const n=String(name||'').toLowerCase(); const m=n.match(/\.(jpg|jpeg|png|webp|heic|heif)$/); if(m)return '.'+m[1]; return ({'image/jpeg':'.jpeg','image/png':'.png','image/webp':'.webp','image/heic':'.heic','image/heif':'.heif'}[String(mime||'').toLowerCase()]||'.jpeg')}
function cleanFilenamePart(v){return safe(v,120)}
function normalizedSource(v){const s=String(v||'').trim();return /^gmail$/i.test(s)?'':s}
const CATS={photos:{suffix:'',label:'Fotografie'},stories:{suffix:'_Stories',label:'Stories'},events:{suffix:'_Events',label:'Events'},contest:{suffix:'_Soutez',label:'Soutěž'}};
function normalizeCategory(v){const x=String(v||'').trim().toLowerCase();return CATS[x]?x:'photos'}
function buildFilename(p, extension='.jpeg'){
  const parts=[cleanFilenamePart(p.photographer),cleanFilenamePart(p.instagram),cleanFilenamePart(normalizedSource(p.source)),cleanFilenamePart(p.airline),cleanFilenamePart(p.aircraft)].filter(Boolean);
  const seq=Number(p.sequence); const suffix=Number.isInteger(seq)&&seq>=2?`_${seq}`:''; const cat=CATS[normalizeCategory(p.category)].suffix;
  return `${parts.length?parts.join('_'):'photo'}${suffix}${cat}${extension}`;
}
function identity(n){return String(n||'').replace(/\.(jpe?g|png|webp|heic|heif)$/i,'').toLowerCase()}

function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function fromB64url(s){const x=String(s).replace(/-/g,'+').replace(/_/g,'/')+'===';const b=atob(x.slice(0,x.length-(x.length%4)));return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function hmac(secret,msg){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(msg)))}
async function signCookie(env,payload){const sig=b64url(await hmac(env.SESSION_SECRET,payload));return b64url(new TextEncoder().encode(`${payload}.${sig}`))}
async function verifyCookie(env,request){const raw=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${ADMIN_COOKIE}=`))?.split('=').slice(1).join('=');if(!raw||!env.SESSION_SECRET)return null;try{const text=new TextDecoder().decode(fromB64url(decodeURIComponent(raw)));const [exp,mail,sig]=text.split('.');if(!exp||Number(exp)<Date.now()||email(mail)!==email(env.ADMIN_EMAIL))return null;const expected=await hmac(env.SESSION_SECRET,`${exp}.${mail}`);const actual=fromB64url(sig);if(expected.length!==actual.length)return null;let d=0;for(let i=0;i<expected.length;i++)d|=expected[i]^actual[i];return d===0?{email:mail}:null}catch{return null}}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${maxAge}`}

function r2Aws(env){return new AwsClient({accessKeyId:env.R2_ACCESS_KEY_ID,secretAccessKey:env.R2_SECRET_ACCESS_KEY,service:'s3',region:'auto'})}
function r2Url(env,key){const endpoint=String(env.R2_S3_ENDPOINT||`https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`).replace(/\/$/,'');return `${endpoint}/${encodeURIComponent(env.R2_BUCKET_NAME||'lv-fa-import')}/${key.split('/').map(encodeURIComponent).join('/')}`}
async function presign(env,key,method,mime){const opts={method,aws:{signQuery:true,expires:900}};if(method==='PUT')opts.headers={'Content-Type':mime};return (await r2Aws(env).sign(r2Url(env,key),opts)).url.toString()}

function oauthRedirect(env,state){const p=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:`${env.PUBLIC_BASE_URL}/api/auth/google/callback`,response_type:'code',scope:'openid email profile',access_type:'online',prompt:'select_account',state});return `https://accounts.google.com/o/oauth2/v2/auth?${p}`}
async function googleToken(env,code){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:`${env.PUBLIC_BASE_URL}/api/auth/google/callback`,grant_type:'authorization_code'})});if(!r.ok)throw new Error('GOOGLE_TOKEN_FAILED');return r.json()}
async function googleUser(access){const r=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw new Error('GOOGLE_USERINFO_FAILED');return r.json()}
async function authRequired(env,request){return verifyCookie(env,request)}

async function sendEmail(env,to,subject,html){if(!env.RESEND_API_KEY||!env.EMAIL_FROM)throw new Error('EMAIL_NOT_CONFIGURED');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject,html})});if(!r.ok)throw new Error(`RESEND_${r.status}`);return r.json()}
function resultEmail(sub,approved,rejected){const subject=`LV-FA / FlyAlert – Výsledek zpracování fotografií / Photo submission result`;const html=`<!doctype html><html><body style="margin:0;background:#f6f6f4;font-family:Arial,sans-serif;color:#111"><div style="max-width:680px;margin:32px auto;background:#fff;border:1px solid #ddd;padding:30px"><h2 style="font-weight:700">Letecký vykřičník &amp; FlyAlert</h2><p><strong>ČESKY</strong></p><p>Dobrý den,</p><p>děkujeme za zaslání fotografií. Z <strong>${sub.total_files}</strong> fotografií bylo <strong>${approved}</strong> vybráno do našeho archivu a <strong>${rejected}</strong> nebylo zařazeno.</p><p>Děkujeme za spolupráci.</p><hr style="border:0;border-top:1px solid #ddd;margin:28px 0"><p><strong>ENGLISH</strong></p><p>Hello,</p><p>thank you for submitting your photographs. Of the <strong>${sub.total_files}</strong> photographs submitted, <strong>${approved}</strong> were selected for our archive and <strong>${rejected}</strong> were not selected.</p><p>Thank you for your cooperation.</p><p style="color:#777;font-size:12px">Letecký vykřičník &amp; FlyAlert</p></div></body></html>`;return {subject,html}}

async function publicCreate(request,env){
 const body=await request.json().catch(()=>({})); const name=safe(body.name,120); const addr=email(body.email); const language=body.language==='en'?'en':'cs'; const files=Array.isArray(body.files)?body.files:[]; const maxFiles=envNumber(env,'MAX_FILES',MAX_FILES_DEFAULT),maxBytes=envNumber(env,'MAX_FILE_MB',MAX_FILE_MB_DEFAULT)*1024*1024;
 if(!name||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(addr))return json({error:'INVALID_CONTACT'},400); if(!files.length||files.length>maxFiles)return json({error:'INVALID_FILE_COUNT',maxFiles},400);
 for(const f of files){if(!f||!isImageMime(f.mimeType)||!f.name||Number(f.size)<=0||Number(f.size)>maxBytes||!f.meta?.photographer||!f.meta?.airline)return json({error:'INVALID_PHOTO_METADATA',message:'Každá fotografie musí mít vyplněné jméno fotografa a aerolinku / letiště.'},400)}
 const id=`IMP-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}-${uuid().slice(0,6).toUpperCase()}`; const created=now(); const stm=[env.DB.prepare('INSERT INTO submissions (id,name,email,language,note,status,total_files,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,name,addr,language,String(body.note||'').slice(0,500),'UPLOADING',files.length,created)]; const rows=[];
 for(const f of files){const pid=uuid();const original=safe(f.name);const key=`imports/${created.slice(0,4)}/${created.slice(5,7)}/${id}/${pid}-${original}`;const m=f.meta||{};rows.push({id:pid,key,original,mime:f.mimeType,size:Number(f.size)});stm.push(env.DB.prepare('INSERT INTO photos (id,submission_id,storage_key,original_name,mime_type,size_bytes,status,photographer,instagram,source,airline,aircraft,note,category,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(pid,id,key,original,f.mimeType,Number(f.size),'UPLOADING',safe(m.photographer,120),safe(m.instagram,120),safe(m.source,160),safe(m.airline,160),safe(m.aircraft,160),safe(m.note,500),normalizeCategory(m.category),created))}
 await env.DB.batch(stm); const uploads=await Promise.all(rows.map(async r=>({id:r.id,name:r.original,uploadUrl:await presign(env,r.key,'PUT',r.mime)})));return json({ok:true,submissionId:id,uploads},201)
}
async function publicComplete(request,env,id){const sub=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!sub)return json({error:'NOT_FOUND'},404);if(sub.status!=='UPLOADING')return json({error:'ALREADY_COMPLETED'},409);const ps=await env.DB.prepare('SELECT * FROM photos WHERE submission_id=?').bind(id).all();for(const p of ps.results||[]){const o=await env.IMPORT_BUCKET.head(p.storage_key);if(!o||Number(o.size)!==Number(p.size_bytes))return json({error:'UPLOAD_INCOMPLETE',photoId:p.id,filename:p.original_name},400)}await env.DB.batch([env.DB.prepare("UPDATE photos SET status='UPLOADED' WHERE submission_id=?").bind(id),env.DB.prepare("UPDATE submissions SET status='READY_FOR_REVIEW',completed_at=? WHERE id=?").bind(now(),id)]);return json({ok:true,submissionId:id})}

async function adminList(request,env){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const r=await env.DB.prepare('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 300').all();return json({submissions:r.results||[]})}
async function adminDetail(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const r=await env.DB.prepare('SELECT * FROM photos WHERE submission_id=? ORDER BY created_at').bind(id).all();return json({submission:s,photos:(r.results||[]).map(p=>({...p,previewUrl:`/api/admin/photos/${encodeURIComponent(p.id)}/preview`}))})}
async function adminUpdatePhoto(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const b=await request.json().catch(()=>({}));const p=await env.DB.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!p)return json({error:'NOT_FOUND'},404);const m={photographer:safe(b.photographer,120),instagram:safe(b.instagram,120),source:safe(b.source,160),airline:safe(b.airline,160),aircraft:safe(b.aircraft,160),note:safe(b.note,500),category:normalizeCategory(b.category)};if(!m.photographer||!m.airline)return json({error:'REQUIRED_FIELDS'},400);await env.DB.prepare('UPDATE photos SET photographer=?,instagram=?,source=?,airline=?,aircraft=?,note=?,category=? WHERE id=?').bind(m.photographer,m.instagram,m.source,m.airline,m.aircraft,m.note,m.category,id).run();return json({ok:true})}
async function maybeSendRejectedOnly(env,id){const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s||s.email_status==='SENT')return;const c=await env.DB.prepare("SELECT SUM(status='APPROVED') approved,SUM(status='REJECTED') rejected,SUM(status='UPLOADED') pending FROM photos WHERE submission_id=?").bind(id).first();if(Number(c?.pending||0)!==0||Number(c?.approved||0)!==0)return;const mail=resultEmail(s,0,Number(c?.rejected||0));try{await sendEmail(env,s.email,mail.subject,mail.html);await env.DB.prepare("UPDATE submissions SET email_status='SENT',email_sent_at=? WHERE id=?").bind(now(),id).run()}catch(e){await env.DB.prepare("UPDATE submissions SET email_status='FAILED',email_error=? WHERE id=?").bind(String(e?.message||e),id).run()}}
async function adminReview(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const b=await request.json().catch(()=>({}));const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const list=Array.isArray(b.photos)?b.photos:[];const stm=[];for(const x of list){if(!['APPROVED','REJECTED','UPLOADED'].includes(x.status))continue;stm.push(env.DB.prepare('UPDATE photos SET status=?,review_note=?,reviewed_at=? WHERE id=? AND submission_id=?').bind(x.status,safe(x.note,500),now(),x.id,id))}if(stm.length)await env.DB.batch(stm);const c=await env.DB.prepare("SELECT SUM(status='APPROVED') approved,SUM(status='REJECTED') rejected,SUM(status='UPLOADED') pending FROM photos WHERE submission_id=?").bind(id).first();const pending=Number(c?.pending||0),approved=Number(c?.approved||0),rejected=Number(c?.rejected||0);const status=pending?'IN_REVIEW':'REVIEWED';await env.DB.prepare('UPDATE submissions SET status=?,approved_files=?,rejected_files=?,review_started_at=COALESCE(review_started_at,?) WHERE id=?').bind(status,approved,rejected,now(),id).run();if(status==='REVIEWED')await maybeSendRejectedOnly(env,id);return json({ok:true,status,approved,rejected,pending})}

function pkcs8ToPem(raw){return raw}
async function googleAccessToken(env){const email=env.GOOGLE_SERVICE_ACCOUNT_EMAIL,keyPem=pkcs8ToPem(env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY||'');if(!email||!keyPem)throw new Error('GOOGLE_SERVICE_ACCOUNT_NOT_CONFIGURED');const pem=keyPem.replace(/\\n/g,'\n');const b64=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s/g,'');const der=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',der,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const enc=v=>b64url(new TextEncoder().encode(v));const head=enc(JSON.stringify({alg:'RS256',typ:'JWT'}));const claim=enc(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/drive',aud:'https://oauth2.googleapis.com/token',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600}));const input=`${head}.${claim}`;const sig=b64url(new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(input))));const jwt=`${input}.${sig}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});if(!r.ok)throw new Error('GOOGLE_SERVICE_TOKEN_FAILED');return (await r.json()).access_token}
async function driveListNames(token,parent){const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(`'${parent.replace(/'/g,"\\'")}' in parents and trashed = false`)}&fields=files(id,name)&pageSize=1000`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('DRIVE_LIST_FAILED');const j=await r.json();return new Set((j.files||[]).map(x=>identity(x.name)))}
async function driveFindOrCreateFolder(token,parent,name){const q=`'${parent.replace(/'/g,"\\'")}' in parents and name='${name.replace(/'/g,"\\'")}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;const r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)&pageSize=10`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('DRIVE_FOLDER_LIST_FAILED');const j=await r.json();if(j.files?.[0]?.id)return j.files[0].id;const c=await fetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name,parents:[parent],mimeType:'application/vnd.google-apps.folder'})});if(!c.ok)throw new Error('DRIVE_FOLDER_CREATE_FAILED');return (await c.json()).id}
async function archiveFolder(token,root,category){const c=normalizeCategory(category);if(c==='photos')return root;return driveFindOrCreateFolder(token,root,CATS[c].label)}
async function driveUpload(token,parent,filename,mime,bytes){const boundary=`lvfa_${uuid()}`;const meta=JSON.stringify({name:filename,parents:[parent],properties:{source:'LV-FA Import'}});const pre=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${meta}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`;const post=`\r\n--${boundary}--`;const body=new Blob([pre,bytes,post]);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!r.ok)throw new Error(`DRIVE_UPLOAD_${r.status}`);return r.json()}
async function adminArchive(request,env,id){if(!await authRequired(env,request))return json({error:'UNAUTHENTICATED'},401);const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'NOT_FOUND'},404);const ps=await env.DB.prepare("SELECT * FROM photos WHERE submission_id=? AND status='APPROVED'").bind(id).all();if(!ps.results?.length)return json({error:'NO_APPROVED_PHOTOS'},400);const token=await googleAccessToken(env);await env.DB.prepare("UPDATE submissions SET status='ARCHIVING',archive_started_at=? WHERE id=?").bind(now(),id).run();let ok=0,failed=0;for(const p of ps.results){try{const o=await env.IMPORT_BUCKET.get(p.storage_key);if(!o)throw new Error('IMPORT_FILE_NOT_FOUND');const parent=await archiveFolder(token,env.GOOGLE_DRIVE_FOLDER_ID,p.category);const existing=await driveListNames(token,parent);const ext=extFrom(p.original_name,p.mime_type);const base={photographer:p.photographer,instagram:p.instagram,source:p.source,airline:p.airline,aircraft:p.aircraft,category:p.category};let filename=buildFilename(base,ext);if(existing.has(identity(filename))){for(let n=2;n<10000;n++){const c=buildFilename({...base,sequence:n},ext);if(!existing.has(identity(c))){filename=c;break}}}if(existing.has(identity(filename)))throw new Error('FILENAME_SEQUENCE_EXHAUSTED');const result=await driveUpload(token,parent,filename,p.mime_type,await o.arrayBuffer());existing.add(identity(filename));await env.DB.prepare("UPDATE photos SET status='ARCHIVED',archive_id=?,archived_at=?,archive_error=NULL WHERE id=?").bind(result.id||'',now(),p.id).run();ok++}catch(e){failed++;await env.DB.prepare("UPDATE photos SET status='ARCHIVE_FAILED',archive_error=? WHERE id=?").bind(String(e?.message||e),p.id).run()}}
const final=failed?'ARCHIVE_FAILED':'ARCHIVED';await env.DB.prepare('UPDATE submissions SET status=?,archive_completed_at=? WHERE id=?').bind(final,now(),id).run();if(!failed){const counts=await env.DB.prepare("SELECT SUM(status='ARCHIVED') approved,SUM(status='REJECTED') rejected FROM photos WHERE submission_id=?").bind(id).first();const mail=resultEmail(s,Number(counts?.approved||ok),Number(counts?.rejected||0));try{await sendEmail(env,s.email,mail.subject,mail.html);await env.DB.prepare("UPDATE submissions SET email_status='SENT',email_sent_at=? WHERE id=?").bind(now(),id).run()}catch(e){await env.DB.prepare("UPDATE submissions SET email_status='FAILED',email_error=? WHERE id=?").bind(String(e?.message||e),id).run()}}return json({ok:true,archived:ok,failed,status:final})}
async function preview(request,env,id){if(!await authRequired(env,request))return new Response('Unauthorized',{status:401});const p=await env.DB.prepare('SELECT * FROM photos WHERE id=?').bind(id).first();if(!p)return new Response('Not found',{status:404});const o=await env.IMPORT_BUCKET.get(p.storage_key);if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'Content-Type':p.mime_type,'Cache-Control':'private,max-age=60'}})}

async function api(request,env){const u=new URL(request.url),p=u.pathname;
 if(request.method==='GET'&&p==='/api/auth/google'){const raw=`${Date.now()+600000}.${uuid()}`;const state=await signCookie(env,raw);return new Response(null,{status:302,headers:{Location:oauthRedirect(env,state),'Set-Cookie':cookie('lvfa_oauth_state',state,600)}})}
 if(request.method==='GET'&&p==='/api/auth/google/callback'){const code=u.searchParams.get('code'),state=u.searchParams.get('state');const stateCookie=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('lvfa_oauth_state='))?.split('=').slice(1).join('=');if(!code||!state||!stateCookie||state!==decodeURIComponent(stateCookie))return Response.redirect(`${env.PUBLIC_BASE_URL}/admin?login=failed`,302);try{const token=await googleToken(env,code);const user=await googleUser(token.access_token);if(email(user.email)!==email(env.ADMIN_EMAIL))return Response.redirect(`${env.PUBLIC_BASE_URL}/admin?login=denied`,302);const value=await signCookie(env,`${Date.now()+1000*60*60*24*7}.${email(user.email)}`);return new Response(null,{status:302,headers:{Location:`${env.PUBLIC_BASE_URL}/admin`, 'Set-Cookie':cookie(ADMIN_COOKIE,value,604800)}})}catch{return Response.redirect(`${env.PUBLIC_BASE_URL}/admin?login=failed`,302)}}
 if(request.method==='POST'&&p==='/api/auth/logout')return new Response(null,{status:204,headers:{'Set-Cookie':cookie(ADMIN_COOKIE,'',0)}});
 if(request.method==='GET'&&p==='/api/auth/me'){const s=await authRequired(env,request);return json(s?{authenticated:true,email:s.email}:{authenticated:false},s?200:401)}
 if(request.method==='POST'&&p==='/api/public/submissions')return publicCreate(request,env);
 if(request.method==='POST'&&p.startsWith('/api/public/submissions/')&&p.endsWith('/complete'))return publicComplete(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='GET'&&p==='/api/admin/submissions')return adminList(request,env);
 if(request.method==='GET'&&p.startsWith('/api/admin/submissions/'))return adminDetail(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='PATCH'&&p.startsWith('/api/admin/photos/'))return adminUpdatePhoto(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='POST'&&p.startsWith('/api/admin/submissions/')&&p.endsWith('/review'))return adminReview(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='POST'&&p.startsWith('/api/admin/submissions/')&&p.endsWith('/archive'))return adminArchive(request,env,decodeURIComponent(p.split('/')[4]));
 if(request.method==='GET'&&p.startsWith('/api/admin/photos/')&&p.endsWith('/preview'))return preview(request,env,decodeURIComponent(p.split('/')[4]));
 return json({error:'NOT_FOUND'},404)}

export default {async fetch(request,env){try{const u=new URL(request.url);if(u.pathname.startsWith('/api/'))return await api(request,env);if(u.pathname==='/admin'||u.pathname==='/admin/')return env.ASSETS.fetch(new Request(new URL('/admin.html',u).toString(),request));return env.ASSETS.fetch(request)}catch(e){console.error(e);return json({error:'INTERNAL_ERROR',message:String(e?.message||e)},500)}}};
